/**
 * MyMemory does not expose a machine-readable language catalogue. This reviewed compatibility
 * list mirrors deep-translator's maintained MyMemory integration as verified on 2026-09-16.
 * Source: https://github.com/nidhaloff/deep-translator/blob/master/deep_translator/constants.py
 */
export const MYMEMORY_LANGUAGE_ENTRIES = [
  { code: "ace-ID", name: "Acehnese" },
  { code: "af-ZA", name: "Afrikaans" },
  { code: "ak-GH", name: "Akan" },
  { code: "sq-AL", name: "Albanian" },
  { code: "am-ET", name: "Amharic" },
  { code: "aig-AG", name: "Antigua And Barbuda Creole English" },
  { code: "ar-SA", name: "Arabic" },
  { code: "ar-EG", name: "Arabic Egyptian" },
  { code: "an-ES", name: "Aragonese" },
  { code: "hy-AM", name: "Armenian" },
  { code: "as-IN", name: "Assamese" },
  { code: "ast-ES", name: "Asturian" },
  { code: "de-AT", name: "Austrian German" },
  { code: "awa-IN", name: "Awadhi" },
  { code: "quy-PE", name: "Ayacucho Quechua" },
  { code: "az-AZ", name: "Azerbaijani" },
  { code: "bah-BS", name: "Bahamas Creole English" },
  { code: "bjs-BB", name: "Bajan" },
  { code: "ban-ID", name: "Balinese" },
  { code: "rm-RO", name: "Balkan Gipsy" },
  { code: "bm-ML", name: "Bambara" },
  { code: "bjn-ID", name: "Banjar" },
  { code: "ba-RU", name: "Bashkir" },
  { code: "eu-ES", name: "Basque" },
  { code: "be-BY", name: "Belarusian" },
  { code: "fr-BE", name: "Belgian French" },
  { code: "bem-ZM", name: "Bemba" },
  { code: "bn-IN", name: "Bengali" },
  { code: "bho-IN", name: "Bhojpuri" },
  { code: "bh-IN", name: "Bihari" },
  { code: "bi-VU", name: "Bislama" },
  { code: "gax-KE", name: "Borana" },
  { code: "bs-BA", name: "Bosnian" },
  { code: "bs-Cyrl-BA", name: "Bosnian (Cyrillic)" },
  { code: "br-FR", name: "Breton" },
  { code: "bug-ID", name: "Buginese" },
  { code: "bg-BG", name: "Bulgarian" },
  { code: "my-MM", name: "Burmese" },
  { code: "ca-ES", name: "Catalan" },
  { code: "cav-ES", name: "Catalan Valencian" },
  { code: "ceb-PH", name: "Cebuano" },
  { code: "tzm-MA", name: "Central Atlas Tamazight" },
  { code: "ayr-BO", name: "Central Aymara" },
  { code: "knc-NG", name: "Central Kanuri (Latin Script)" },
  { code: "shu-TD", name: "Chadian Arabic" },
  { code: "ch-GU", name: "Chamorro" },
  { code: "chr-US", name: "Cherokee" },
  { code: "hne-IN", name: "Chhattisgarhi" },
  { code: "zh-CN", name: "Chinese Simplified" },
  { code: "zh-HK", name: "Chinese Trad. (Hong Kong)" },
  { code: "zh-TW", name: "Chinese Traditional" },
  { code: "zh-MO", name: "Chinese Traditional Macau" },
  { code: "ctg-BD", name: "Chittagonian" },
  { code: "cjk-AO", name: "Chokwe" },
  { code: "grc-GR", name: "Classical Greek" },
  { code: "zdj-KM", name: "Comorian Ngazidja" },
  { code: "cop-EG", name: "Coptic" },
  { code: "crh-RU", name: "Crimean Tatar" },
  { code: "pov-GW", name: "Crioulo Upper Guinea" },
  { code: "hr-HR", name: "Croatian" },
  { code: "cs-CZ", name: "Czech" },
  { code: "da-DK", name: "Danish" },
  { code: "prs-AF", name: "Dari" },
  { code: "diq-TR", name: "Dimli" },
  { code: "nl-NL", name: "Dutch" },
  { code: "dyu-CI", name: "Dyula" },
  { code: "dz-BT", name: "Dzongkha" },
  { code: "ydd-US", name: "Eastern Yiddish" },
  { code: "vmw-MZ", name: "Emakhuwa" },
  { code: "en-GB", name: "English" },
  { code: "en-AU", name: "English Australia" },
  { code: "en-CA", name: "English Canada" },
  { code: "en-IN", name: "English India" },
  { code: "en-IE", name: "English Ireland" },
  { code: "en-NZ", name: "English New Zealand" },
  { code: "en-SG", name: "English Singapore" },
  { code: "en-ZA", name: "English South Africa" },
  { code: "en-US", name: "English US" },
  { code: "eo-EU", name: "Esperanto" },
  { code: "et-EE", name: "Estonian" },
  { code: "ee-GH", name: "Ewe" },
  { code: "fn-FNG", name: "Fanagalo" },
  { code: "fo-FO", name: "Faroese" },
  { code: "fj-FJ", name: "Fijian" },
  { code: "fil-PH", name: "Filipino" },
  { code: "fi-FI", name: "Finnish" },
  { code: "nl-BE", name: "Flemish" },
  { code: "fon-BJ", name: "Fon" },
  { code: "fr-FR", name: "French" },
  { code: "fr-CA", name: "French Canada" },
  { code: "fr-CH", name: "French Swiss" },
  { code: "fur-IT", name: "Friulian" },
  { code: "ff-FUL", name: "Fula" },
  { code: "gl-ES", name: "Galician" },
  { code: "mfi-NG", name: "Gamargu" },
  { code: "grt-IN", name: "Garo" },
  { code: "ka-GE", name: "Georgian" },
  { code: "de-DE", name: "German" },
  { code: "gil-KI", name: "Gilbertese" },
  { code: "glw-NG", name: "Glavda" },
  { code: "el-GR", name: "Greek" },
  { code: "gcl-GD", name: "Grenadian Creole English" },
  { code: "gn-PY", name: "Guarani" },
  { code: "gu-IN", name: "Gujarati" },
  { code: "gyn-GY", name: "Guyanese Creole English" },
  { code: "ht-HT", name: "Haitian Creole French" },
  { code: "khk-MN", name: "Halh Mongolian" },
  { code: "ha-NE", name: "Hausa" },
  { code: "haw-US", name: "Hawaiian" },
  { code: "he-IL", name: "Hebrew" },
  { code: "hig-NG", name: "Higi" },
  { code: "hil-PH", name: "Hiligaynon" },
  { code: "mrj-RU", name: "Hill Mari" },
  { code: "hi-IN", name: "Hindi" },
  { code: "hmn-CN", name: "Hmong" },
  { code: "hu-HU", name: "Hungarian" },
  { code: "is-IS", name: "Icelandic" },
  { code: "ibo-NG", name: "Igbo IBO" },
  { code: "ig-NG", name: "Igbo IG" },
  { code: "ilo-PH", name: "Ilocano" },
  { code: "id-ID", name: "Indonesian" },
  { code: "kl-GL", name: "Inuktitut Greenlandic" },
  { code: "ga-IE", name: "Irish Gaelic" },
  { code: "it-IT", name: "Italian" },
  { code: "it-CH", name: "Italian Swiss" },
  { code: "jam-JM", name: "Jamaican Creole English" },
  { code: "ja-JP", name: "Japanese" },
  { code: "jv-ID", name: "Javanese" },
  { code: "kac-MM", name: "Jingpho" },
  { code: "quc-GT", name: "K'iche'" },
  { code: "kbp-TG", name: "Kabiyè" },
  { code: "kea-CV", name: "Kabuverdianu" },
  { code: "kab-DZ", name: "Kabylian" },
  { code: "kln-KE", name: "Kalenjin" },
  { code: "kam-KE", name: "Kamba" },
  { code: "kn-IN", name: "Kannada" },
  { code: "kr-KAU", name: "Kanuri" },
  { code: "kar-MM", name: "Karen" },
  { code: "ks-IN", name: "Kashmiri (Devanagari Script)" },
  { code: "kas-IN", name: "Kashmiri (Arabic Script)" },
  { code: "kk-KZ", name: "Kazakh" },
  { code: "kha-IN", name: "Khasi" },
  { code: "km-KH", name: "Khmer" },
  { code: "kik-KE", name: "Kikuyu Kik" },
  { code: "ki-KE", name: "Kikuyu Ki" },
  { code: "kmb-AO", name: "Kimbundu" },
  { code: "rw-RW", name: "Kinyarwanda" },
  { code: "rn-BI", name: "Kirundi" },
  { code: "guz-KE", name: "Kisii" },
  { code: "kg-CG", name: "Kongo" },
  { code: "kok-IN", name: "Konkani" },
  { code: "ko-KR", name: "Korean" },
  { code: "kmr-TR", name: "Northern Kurdish" },
  { code: "ckb-IQ", name: "Kurdish Sorani" },
  { code: "ky-KG", name: "Kyrgyz" },
  { code: "lo-LA", name: "Lao" },
  { code: "ltg-LV", name: "Latgalian" },
  { code: "la-XN", name: "Latin" },
  { code: "lv-LV", name: "Latvian" },
  { code: "lij-IT", name: "Ligurian" },
  { code: "li-NL", name: "Limburgish" },
  { code: "ln-LIN", name: "Lingala" },
  { code: "lt-LT", name: "Lithuanian" },
  { code: "lmo-IT", name: "Lombard" },
  { code: "lua-CD", name: "Luba-Kasai" },
  { code: "lg-UG", name: "Luganda" },
  { code: "luy-KE", name: "Luhya" },
  { code: "luo-KE", name: "Luo" },
  { code: "lb-LU", name: "Luxembourgish" },
  { code: "mas-KE", name: "Maa" },
  { code: "mk-MK", name: "Macedonian" },
  { code: "mag-IN", name: "Magahi" },
  { code: "mai-IN", name: "Maithili" },
  { code: "mg-MG", name: "Malagasy" },
  { code: "ms-MY", name: "Malay" },
  { code: "ml-IN", name: "Malayalam" },
  { code: "dv-MV", name: "Maldivian" },
  { code: "mt-MT", name: "Maltese" },
  { code: "mfi-CM", name: "Mandara" },
  { code: "mni-IN", name: "Manipuri" },
  { code: "gv-IM", name: "Manx Gaelic" },
  { code: "mi-NZ", name: "Maori" },
  { code: "mr-IN", name: "Marathi" },
  { code: "mrt-NG", name: "Margi" },
  { code: "mhr-RU", name: "Mari" },
  { code: "mh-MH", name: "Marshallese" },
  { code: "men-SL", name: "Mende" },
  { code: "mer-KE", name: "Meru" },
  { code: "nyf-KE", name: "Mijikenda" },
  { code: "min-ID", name: "Minangkabau" },
  { code: "lus-IN", name: "Mizo" },
  { code: "mn-MN", name: "Mongolian" },
  { code: "sr-ME", name: "Montenegrin" },
  { code: "mfe-MU", name: "Morisyen" },
  { code: "ar-MA", name: "Moroccan Arabic" },
  { code: "mos-BF", name: "Mossi" },
  { code: "ndc-MZ", name: "Ndau" },
  { code: "nr-ZA", name: "Ndebele" },
  { code: "ne-NP", name: "Nepali" },
  { code: "fuv-NG", name: "Nigerian Fulfulde" },
  { code: "niu-NU", name: "Niuean" },
  { code: "azj-AZ", name: "North Azerbaijani" },
  { code: "nso-ZA", name: "Sesotho" },
  { code: "uzn-UZ", name: "Northern Uzbek" },
  { code: "nb-NO", name: "Norwegian Bokmål" },
  { code: "nn-NO", name: "Norwegian Nynorsk" },
  { code: "nus-SS", name: "Nuer" },
  { code: "ny-MW", name: "Nyanja" },
  { code: "oc-FR", name: "Occitan" },
  { code: "oc-ES", name: "Occitan Aran" },
  { code: "or-IN", name: "Odia" },
  { code: "ory-IN", name: "Oriya" },
  { code: "ur-PK", name: "Urdu" },
  { code: "pau-PW", name: "Palauan" },
  { code: "pi-IN", name: "Pali" },
  { code: "pag-PH", name: "Pangasinan" },
  { code: "pap-CW", name: "Papiamentu" },
  { code: "ps-PK", name: "Pashto" },
  { code: "fa-IR", name: "Persian" },
  { code: "pis-SB", name: "Pijin" },
  { code: "plt-MG", name: "Plateau Malagasy" },
  { code: "pl-PL", name: "Polish" },
  { code: "pt-PT", name: "Portuguese" },
  { code: "pt-BR", name: "Portuguese Brazil" },
  { code: "pot-US", name: "Potawatomi" },
  { code: "pa-IN", name: "Punjabi" },
  { code: "pnb-PK", name: "Punjabi (Pakistan)" },
  { code: "qu-PE", name: "Quechua" },
  { code: "rhg-MM", name: "Rohingya" },
  { code: "rhl-MM", name: "Rohingyalish" },
  { code: "ro-RO", name: "Romanian" },
  { code: "roh-CH", name: "Romansh" },
  { code: "run-BI", name: "Rundi" },
  { code: "ru-RU", name: "Russian" },
  { code: "acf-LC", name: "Saint Lucian Creole French" },
  { code: "sm-WS", name: "Samoan" },
  { code: "sg-CF", name: "Sango" },
  { code: "sa-IN", name: "Sanskrit" },
  { code: "sat-IN", name: "Santali" },
  { code: "sc-IT", name: "Sardinian" },
  { code: "gd-GB", name: "Scots Gaelic" },
  { code: "seh-ZW", name: "Sena" },
  { code: "sr-Cyrl-RS", name: "Serbian Cyrillic" },
  { code: "sr-Latn-RS", name: "Serbian Latin" },
  { code: "crs-SC", name: "Seselwa Creole French" },
  { code: "tn-ZA", name: "Setswana (South Africa)" },
  { code: "shn-MM", name: "Shan" },
  { code: "sn-ZW", name: "Shona" },
  { code: "scn-IT", name: "Sicilian" },
  { code: "szl-PL", name: "Silesian" },
  { code: "snd-PK", name: "Sindhi SND" },
  { code: "sd-PK", name: "Sindhi SD" },
  { code: "si-LK", name: "Sinhala" },
  { code: "sk-SK", name: "Slovak" },
  { code: "sl-SI", name: "Slovenian" },
  { code: "so-SO", name: "Somali" },
  { code: "st-LS", name: "Sotho Southern" },
  { code: "azb-AZ", name: "South Azerbaijani" },
  { code: "pbt-PK", name: "Southern Pashto" },
  { code: "dik-SS", name: "Southwestern Dinka" },
  { code: "es-ES", name: "Spanish" },
  { code: "es-AR", name: "Spanish Argentina" },
  { code: "es-CO", name: "Spanish Colombia" },
  { code: "es-419", name: "Spanish Latin America" },
  { code: "es-MX", name: "Spanish Mexico" },
  { code: "es-US", name: "Spanish United States" },
  { code: "srn-SR", name: "Sranan Tongo" },
  { code: "lvs-LV", name: "Standard Latvian" },
  { code: "zsm-MY", name: "Standard Malay" },
  { code: "su-ID", name: "Sundanese" },
  { code: "sw-KE", name: "Swahili" },
  { code: "ss-SZ", name: "Swati" },
  { code: "sv-SE", name: "Swedish" },
  { code: "de-CH", name: "Swiss German" },
  { code: "syc-TR", name: "Syriac (Aramaic)" },
  { code: "tl-PH", name: "Tagalog" },
  { code: "ty-PF", name: "Tahitian" },
  { code: "tg-TJ", name: "Tajik" },
  { code: "tmh-DZ", name: "Tamashek (Tuareg)" },
  { code: "taq-ML", name: "Tamasheq" },
  { code: "ta-IN", name: "Tamil India" },
  { code: "ta-LK", name: "Tamil Sri Lanka" },
  { code: "trv-TW", name: "Taroko" },
  { code: "tt-RU", name: "Tatar" },
  { code: "te-IN", name: "Telugu" },
  { code: "tet-TL", name: "Tetum" },
  { code: "th-TH", name: "Thai" },
  { code: "bo-CN", name: "Tibetan" },
  { code: "ti-ET", name: "Tigrinya" },
  { code: "tpi-PG", name: "Tok Pisin" },
  { code: "tkl-TK", name: "Tokelauan" },
  { code: "to-TO", name: "Tongan" },
  { code: "als-AL", name: "Tosk Albanian" },
  { code: "ts-ZA", name: "Tsonga" },
  { code: "tsc-MZ", name: "Tswa" },
  { code: "tn-BW", name: "Tswana" },
  { code: "tum-MW", name: "Tumbuka" },
  { code: "tr-TR", name: "Turkish" },
  { code: "tk-TM", name: "Turkmen" },
  { code: "tvl-TV", name: "Tuvaluan" },
  { code: "tw-GH", name: "Twi" },
  { code: "udm-RU", name: "Udmurt" },
  { code: "uk-UA", name: "Ukrainian" },
  { code: "ppk-ID", name: "Uma" },
  { code: "umb-AO", name: "Umbundu" },
  { code: "uig-CN", name: "Uyghur UIG" },
  { code: "ug-CN", name: "Uyghur UG" },
  { code: "uz-UZ", name: "Uzbek" },
  { code: "vec-IT", name: "Venetian" },
  { code: "vi-VN", name: "Vietnamese" },
  { code: "svc-VC", name: "Vincentian Creole English" },
  { code: "vic-US", name: "Virgin Islands Creole English" },
  { code: "wls-WF", name: "Wallisian" },
  { code: "war-PH", name: "Waray (Philippines)" },
  { code: "cy-GB", name: "Welsh" },
  { code: "gaz-ET", name: "West Central Oromo" },
  { code: "pes-IR", name: "Western Persian" },
  { code: "wo-SN", name: "Wolof" },
  { code: "xh-ZA", name: "Xhosa" },
  { code: "yi-YD", name: "Yiddish" },
  { code: "yo-NG", name: "Yoruba" },
  { code: "zu-ZA", name: "Zulu" },
] as const;
