export interface RomanizedNepaliNormalization {
  confidence: number;
  matchedTokens: number;
  text: string;
  totalTokens: number;
}

const WORDS: Readonly<Record<string, string>> = {
  aafai: "आफै",
  aafno: "आफ्नो",
  aaja: "आज",
  aama: "आमा",
  aba: "अब",
  agadi: "अगाडि",
  ani: "अनि",
  arko: "अर्को",
  asti: "अस्ति",
  aucha: "आउँछ",
  audai: "आउँदै",
  bacha: "बच्चा",
  baira: "बाहिर",
  bajar: "बजार",
  baje: "बजे",
  bhan: "भन",
  bhancha: "भन्छ",
  bhandai: "भन्दै",
  bhane: "भने",
  bhaneko: "भनेको",
  bhannu: "भन्नु",
  bhaat: "भात",
  bhat: "भात",
  bhayo: "भयो",
  bhetaula: "भेटौँला",
  bholi: "भोलि",
  bichar: "विचार",
  birami: "बिरामी",
  birse: "बिर्से",
  bujhe: "बुझे",
  bujhina: "बुझिन",
  bujnu: "बुझ्नु",
  chadai: "चाँडै",
  chahanchu: "चाहन्छु",
  chahincha: "चाहिन्छ",
  chaina: "छैन",
  cha: "छ",
  chha: "छ",
  chhaina: "छैन",
  chhau: "छौ",
  chhu: "छु",
  chito: "छिटो",
  chori: "छोरी",
  chora: "छोरा",
  dai: "दाइ",
  didi: "दिदी",
  din: "दिन",
  dinu: "दिनु",
  dherai: "धेरै",
  dukha: "दुःख",
  farkanchu: "फर्कन्छु",
  farkidai: "फर्किँदै",
  farkina: "फर्किन",
  farkiye: "फर्किए",
  feri: "फेरि",
  garchha: "गर्छ",
  garchhu: "गर्छु",
  garchu: "गर्छु",
  gardai: "गर्दै",
  gare: "गरे",
  gareko: "गरेको",
  garna: "गर्न",
  garnu: "गर्नु",
  garxu: "गर्छु",
  garxau: "गर्छौ",
  gaun: "गाउँ",
  gaye: "गए",
  gayo: "गयो",
  ghar: "घर",
  ghara: "घर",
  gharma: "घरमा",
  hami: "हामी",
  hajur: "हजुर",
  hajurlai: "हजुरलाई",
  hera: "हेर",
  herchu: "हेर्छु",
  herdai: "हेर्दै",
  herna: "हेर्न",
  hijo: "हिजो",
  ho: "हो",
  hunchha: "हुन्छ",
  huncha: "हुन्छ",
  hunchu: "हुन्छु",
  hunu: "हुनु",
  jancha: "जान्छ",
  janchha: "जान्छ",
  janchhu: "जान्छु",
  janchu: "जान्छु",
  janchau: "जान्छौ",
  jandai: "जाँदै",
  jane: "जाने",
  janey: "जाने",
  jadai: "जाँदै",
  jana: "जान",
  jasto: "जस्तो",
  jhan: "झन्",
  kaam: "काम",
  kahile: "कहिले",
  kahilekahi: "कहिलेकाहीँ",
  kaha: "कहाँ",
  kasari: "कसरी",
  kaso: "कसो",
  kasto: "कस्तो",
  kati: "कति",
  ke: "के",
  k: "के",
  kehi: "केही",
  khai: "खै",
  khana: "खान",
  khanchu: "खान्छु",
  khadai: "खाँदै",
  khadaichhu: "खाँदै छु",
  khadaichu: "खाँदै छु",
  khane: "खाने",
  khayera: "खाएर",
  khojchu: "खोज्छु",
  khojdai: "खोज्दै",
  khojna: "खोज्न",
  kina: "किन",
  kitaab: "किताब",
  kitab: "किताब",
  la: "ल",
  lagcha: "लाग्छ",
  lagchha: "लाग्छ",
  lagyo: "लाग्यो",
  lai: "लाई",
  laijau: "लैजाऊ",
  lyaunu: "ल्याउनु",
  ma: "म",
  manche: "मान्छे",
  manchhe: "मान्छे",
  maya: "माया",
  mero: "मेरो",
  milcha: "मिल्छ",
  milchha: "मिल्छ",
  milena: "मिलेन",
  mitho: "मीठो",
  namaskar: "नमस्कार",
  namaste: "नमस्ते",
  naam: "नाम",
  nam: "नाम",
  naramro: "नराम्रो",
  naya: "नयाँ",
  pardaina: "पर्दैन",
  parcha: "पर्छ",
  parchha: "पर्छ",
  parkha: "पर्ख",
  paxi: "पछि",
  pheri: "फेरि",
  pugcha: "पुग्छ",
  pugchha: "पुग्छ",
  pugchu: "पुग्छु",
  pugyo: "पुग्यो",
  r: "र",
  ramailo: "रमाइलो",
  ramro: "राम्रो",
  sahi: "सही",
  sakchha: "सक्छ",
  sakcha: "सक्छ",
  sakchhu: "सक्छु",
  sakchu: "सक्छु",
  sakdaina: "सक्दैन",
  sakina: "सकिन",
  samaya: "समय",
  samma: "सम्म",
  sathi: "साथी",
  sanga: "सँग",
  sangai: "सँगै",
  sanchai: "सन्चै",
  school: "स्कूल",
  sano: "सानो",
  sarai: "सारै",
  sikchu: "सिक्छु",
  sikna: "सिक्न",
  ta: "त",
  tapaiko: "तपाईंको",
  tapai: "तपाईं",
  tapailai: "तपाईंलाई",
  thaha: "थाहा",
  thik: "ठीक",
  timi: "तिमी",
  timilai: "तिमीलाई",
  timro: "तिम्रो",
  tyo: "त्यो",
  uni: "उनी",
  uslai: "उसलाई",
  yaha: "यहाँ",
  yahaan: "यहाँ",
  yo: "यो",
};

const VARIANTS: Readonly<Record<string, string>> = {
  aafu: "aafai",
  afai: "aafai",
  afno: "aafno",
  aja: "aaja",
  ajaa: "aaja",
  aune: "aucha",
  auxa: "aucha",
  bhanna: "bhannu",
  bhaneko: "bhaneko",
  bujhnu: "bujnu",
  chaaina: "chaina",
  chhain: "chaina",
  chhaina: "chaina",
  chhuu: "chhu",
  chu: "chhu",
  chuu: "chhu",
  xaina: "chaina",
  xa: "cha",
  xau: "chhau",
  xu: "chhu",
  dina: "dinu",
  dherae: "dherai",
  ekdam: "sarai",
  gar6u: "garchhu",
  garchu: "garchhu",
  garxau: "garchau",
  garxu: "garchhu",
  ghari: "ghar",
  hunchha: "huncha",
  hunxa: "huncha",
  hunxu: "hunchu",
  jan6u: "janchhu",
  jaanchu: "janchhu",
  jaanchhu: "janchhu",
  jaanxu: "janchhu",
  janchu: "janchhu",
  janxu: "janchhu",
  kcha: "cha",
  kastocha: "kasto",
  khaadai: "khadai",
  khaadaichhu: "khadaichhu",
  khaadaichu: "khadaichu",
  khanchhu: "khanchu",
  khanxu: "khanchu",
  khojchhu: "khojchu",
  khojxu: "khojchu",
  maile: "ma",
  malai: "ma",
  merai: "mero",
  nam: "naam",
  parchha: "parcha",
  parxa: "parcha",
  paxi: "paxi",
  pachhi: "paxi",
  pachi: "paxi",
  ramrai: "ramro",
  sanchai: "sanchai",
  sanchha: "sanchai",
  sanchaii: "sanchai",
  sakchhu: "sakchhu",
  sakchu: "sakchhu",
  sakxu: "sakchhu",
  tapain: "tapai",
  tapaiilai: "tapailai",
  thikai: "thik",
  timilaii: "timilai",
};

const TOKEN = /[\p{L}0-9]+|[^\p{L}0-9]+/gu;
const LATIN_WORD = /^[A-Za-z0-9]+$/u;

function normalizeToken(token: string): string {
  return token
    .toLocaleLowerCase()
    .replaceAll("6", "chh")
    .replaceAll(/[^a-z0-9]/gu, "");
}

function lookup(token: string): string | null {
  const normalized = normalizeToken(token);
  const canonical = VARIANTS[normalized] ?? normalized;
  return WORDS[canonical] ?? null;
}

export function normalizeRomanizedNepali(text: string): RomanizedNepaliNormalization | null {
  const pieces = text.match(TOKEN) ?? [];
  let matchedTokens = 0;
  let totalTokens = 0;
  let converted = "";

  for (const piece of pieces) {
    if (!LATIN_WORD.test(piece)) {
      converted += piece;
      continue;
    }
    totalTokens += 1;
    const replacement = lookup(piece);
    if (replacement) {
      matchedTokens += 1;
      converted += replacement;
    } else {
      converted += piece;
    }
  }

  if (totalTokens === 0 || matchedTokens < 2) return null;
  const confidence = matchedTokens / totalTokens;
  if (confidence < 0.55) return null;
  return {
    confidence,
    matchedTokens,
    text: converted,
    totalTokens,
  };
}
